module.exports = {
  siteUrl: process.env.SITE_URL || "https://brewww.studio",
  generateRobotsTxt: true,
  sitemapSize: 7000,
  generateIndexSitemap: false,
  exclude: [
    "/test",
    "/home",
    "/about",
    "/services",
    "/services/*",
    "/contact",
    "/blog",
    "/play",
    "/work",
    "/product",
    "/work/*",
    "/why-brewww",
    "/clients",
    "/styles",
  ],
};
